spring:
  profiles:
    include: jdbc
  cors:
    allow-origin:
    allow-methods:
      - POST
      - GET
      - DELETE
    allow-headers:
      - Token
    allow-credentials: true

mail:
  smtp-server:
  smtp-username:
  smtp-password:
  smtp-port:
  secure-smtp: true
  session-debug: true