spring:
  profiles:
    include: jdbc
  cors:
    allow-origin:
      - http://localhost:8000
    allow-methods:
      - POST
      - GET
      - DELETE
      - OPTIONS
    allow-headers:
      - Token
      - Content-type
    allow-credentials: true

mail:
  smtp-server:
  smtp-username:
  smtp-password:
  smtp-port:
  secure-smtp: true
  session-debug: true