spring:
  profiles:
    include: jdbc
  cors:
    allow-origin:
      - http://localhost:8000
    allow-methods:
      - POST
      - GET
      - DELETE
      - OPTIONS
    allow-headers:
      - Token
      - Content-type
    allow-credentials: true
  # Represent the i18n folder in the classpath with the file prefix messages
  messages:
    basename: i18n.messages
    encoding: UTF-8

mail:
  smtp-server:
  smtp-username:
  smtp-password:
  smtp-port:
  secure-smtp: true
  session-debug: true

redis:
  address: redis://127.0.0.1:6379
  password: 123456
  maxIdle: 10
  maxTotal: 30
  maxWaitMillis: 300000
  testOnBorrow: true
  timeout: 200