spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/octopus_db?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: a123456
    sql-script-encoding: UTF-8